#Eureka Server PORT
server:
  port: 8761

#Spring Cloud ID
spring:
  application:
    name: discoveryService

#Server info
eureka:
  client:
    register-with-eureka: false  #Eureka register use
    fetch-registry: false
